defaults:
  - _self_
  - optimizer: adam.yaml

_target_: tokan.yirga.models.dp_wrapper.DurationPredictorWrapper
# n_vocab: 1000  # Number of HuBERT K-means clusters
# spk_emb_dim: 256

# encoder_type: ${model.encoder.encoder_type}
# encoder_params: ${model.encoder.encoder_params}

yirga_checkpoint: ??? # Path to the trained parameters of the Yirga token-to-Mel model

# duration_predictor_params:
#   dp_type: regression
#   n_layers: 3
#   input_channels: 512
#   n_channels: 256
#   kernel_size: 3
#   p_dropout: 0.2
#   log_scale: true

duration_predictor_params:
  dp_type: flow_matching
  n_layers: 4
  input_channels: 512
  n_channels: 256
  n_heads: 4
  p_dropout: 0.1
  log_scale: false
  training_cfg_rate: 0.2  # Probability of condition dropout (classifier-free guidance)
  inference_cfg_rate: 0.5 # Strength of classifier-free guidance during inference
