encoder_type: RoPE Encoder
encoder_params:
  n_feats: ${model.n_feats}
  n_channels: 256
  filter_channels: 1024
  filter_channels_dp: 384
  n_heads: 4
  n_layers: 6
  kernel_size: 3
  p_dropout: 0.1
  prenet: true

duration_predictor_params:
  filter_channels_dp: ${model.encoder.encoder_params.filter_channels_dp}
  kernel_size: 3
  p_dropout: ${model.encoder.encoder_params.p_dropout}
